# Generated by Django 5.2.4 on 2025-07-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_options_alter_post_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes_count",
            field=models.PositiveIntegerField(default=0, verbose_name="点赞数"),
        ),
        migrations.AddField(
            model_name="post",
            name="replies_count",
            field=models.PositiveIntegerField(default=0, verbose_name="回复数"),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="标签名称")),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("company", "公司"),
                            ("position", "岗位"),
                            ("skill", "技能"),
                            ("industry", "行业"),
                            ("level", "级别"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="标签类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="标签描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
                "ordering": ["tag_type", "name"],
                "unique_together": {("name", "tag_type")},
            },
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="posts.tag", verbose_name="标签"
            ),
        ),
    ]
