# Generated by Django 5.2.4 on 2025-07-21 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_avatar_user_phone_resume_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resume",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "简历",
                "verbose_name_plural": "简历",
            },
        ),
        migrations.AddField(
            model_name="resume",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="是否完成"),
        ),
        migrations.AddField(
            model_name="resume",
            name="resume_name",
            field=models.CharField(
                default="默认简历", max_length=100, verbose_name="简历名称"
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="age",
            field=models.IntegerField(blank=True, null=True, verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="education_level",
            field=models.CharField(blank=True, max_length=50, verbose_name="学历"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="expected_position",
            field=models.CharField(blank=True, max_length=100, verbose_name="期望职位"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="graduation_date",
            field=models.DateField(blank=True, null=True, verbose_name="毕业时间"),
        ),
        migrations.AlterField(
            model_name="resume",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resume",
            unique_together={("user", "resume_name")},
        ),
    ]
