# Generated by Django 5.2.4 on 2025-07-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_resume_options_resume_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="target_company_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="目标公司名称"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="target_position_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="目标岗位ID"),
        ),
        migrations.AddField(
            model_name="user",
            name="target_position_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="目标岗位名称"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="target_salary_max",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="期望最高薪资(k)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="target_salary_min",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="期望最低薪资(k)"
            ),
        ),
    ]
