# Generated by Django 5.2.4 on 2025-07-13 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_alter_user_options_user_avatar_user_phone_resume_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="岗位名称")),
                (
                    "company_name",
                    models.CharField(max_length=100, verbose_name="公司名称"),
                ),
                ("description", models.TextField(verbose_name="岗位详细信息")),
                (
                    "requirements",
                    models.TextField(blank=True, null=True, verbose_name="岗位要求"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "岗位",
                "verbose_name_plural": "岗位",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.JSONField(verbose_name="生成的问题列表")),
                ("generation_context", models.TextField(verbose_name="生成上下文")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.resume",
                        verbose_name="简历",
                    ),
                ),
                (
                    "job_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge_base.jobposition",
                        verbose_name="岗位",
                    ),
                ),
            ],
            options={
                "verbose_name": "面试问题",
                "verbose_name_plural": "面试问题",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBaseEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="问题内容")),
                ("answer", models.TextField(verbose_name="标准答案")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "技术类"),
                            ("behavioral", "行为类"),
                            ("project", "项目类"),
                            ("leadership", "领导力类"),
                            ("general", "通用类"),
                        ],
                        max_length=20,
                        verbose_name="问题类别",
                    ),
                ),
                (
                    "difficulty_level",
                    models.IntegerField(
                        choices=[(1, "L1"), (2, "L2"), (3, "L3"), (4, "L4"), (5, "L5")],
                        verbose_name="难度等级",
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="标签")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "related_positions",
                    models.ManyToManyField(
                        blank=True,
                        to="knowledge_base.jobposition",
                        verbose_name="相关岗位",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库条目",
                "verbose_name_plural": "知识库条目",
                "ordering": ["-created_at"],
            },
        ),
    ]
