# Generated by Django 5.2.4 on 2025-07-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposition",
            name="position_type",
            field=models.CharField(
                choices=[
                    ("backend", "后端开发"),
                    ("frontend", "前端开发"),
                    ("pm", "产品经理"),
                    ("qa", "测试"),
                    ("algo", "算法"),
                ],
                default="backend",
                max_length=20,
                verbose_name="岗位类型",
            ),
        ),
        migrations.AddField(
            model_name="knowledgebaseentry",
            name="company_name",
            field=models.CharField(default="", max_length=100, verbose_name="出题公司"),
        ),
        migrations.AddField(
            model_name="knowledgebaseentry",
            name="position_type",
            field=models.CharField(
                choices=[
                    ("backend", "后端开发"),
                    ("frontend", "前端开发"),
                    ("pm", "产品经理"),
                    ("qa", "测试"),
                    ("algo", "算法"),
                ],
                default="backend",
                max_length=20,
                verbose_name="岗位类型",
            ),
        ),
    ]
