# Generated by Django 5.2.4 on 2025-07-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255, verbose_name='职位名称')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('position_url', models.TextField(verbose_name='职位链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'nowcoder_data',
                'managed': False,  # 告诉Django这个表已经存在，不需要管理
            },
        ),
    ]
