# Generated by Django 5.2.4 on 2025-07-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={
                "managed": False,
                "ordering": ["-id"],
                "verbose_name": "职位信息",
                "verbose_name_plural": "职位信息",
            },
        ),
    ]
