# Generated by Django 5.2.4 on 2025-07-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0003_alter_position_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="NowCoderPosition",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("job_name", models.CharField(max_length=500, verbose_name="职位名称")),
                ("company", models.CharField(max_length=255, verbose_name="公司名称")),
                ("url", models.TextField(verbose_name="职位链接")),
                (
                    "salary",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="薪资"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="地址"),
                ),
                (
                    "view_rate",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="简历处理率"
                    ),
                ),
                (
                    "ave_speed",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="平均处理时间",
                    ),
                ),
                (
                    "add_info",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="附加信息"
                    ),
                ),
                (
                    "work_style",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="工作类型"
                    ),
                ),
                (
                    "work_time",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="工作时间"
                    ),
                ),
                (
                    "upgrade_chance",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="晋升机会"
                    ),
                ),
                (
                    "introduction",
                    models.TextField(blank=True, null=True, verbose_name="职位介绍"),
                ),
                (
                    "job_request",
                    models.TextField(blank=True, null=True, verbose_name="职位要求"),
                ),
            ],
            options={
                "verbose_name": "牛客网职位信息",
                "verbose_name_plural": "牛客网职位信息",
                "db_table": "nowcoder_data",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="position",
            options={
                "managed": True,
                "ordering": ["-id"],
                "verbose_name": "职位信息（已废弃）",
                "verbose_name_plural": "职位信息（已废弃）",
            },
        ),
        migrations.AlterModelTable(
            name="position",
            table="positions_position",
        ),
    ]
