# Generated by Django 5.2.4 on 2025-07-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0004_nowcoderposition_alter_position_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={
                "managed": True,
                "ordering": ["-id"],
                "verbose_name": "职位信息",
                "verbose_name_plural": "职位信息",
            },
        ),
        migrations.AlterField(
            model_name="position",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name="position",
            table="nowcoder_data",
        ),
    ]
