# Generated by Django 5.2.4 on 2025-07-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0005_alter_position_options_alter_position_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={
                "managed": True,
                "ordering": ["-id"],
                "verbose_name": "职位信息（已废弃）",
                "verbose_name_plural": "职位信息（已废弃）",
            },
        ),
        migrations.AlterField(
            model_name="position",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterModelTable(
            name="position",
            table="positions_position",
        ),
    ]
