# Generated by Django 5.2.4 on 2025-07-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0009_alter_position_options_alter_position_id_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="position",
            table="nowcoder_data",
        ),
    ]
