# Generated by Django 5.2.4 on 2025-07-12 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoStream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="流标题")),
                ("description", models.TextField(blank=True, verbose_name="流描述")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="是否活跃"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_streams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "视频流",
                "verbose_name_plural": "视频流",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoFrame",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("frame_data", models.BinaryField(verbose_name="帧数据")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
                (
                    "frame_type",
                    models.CharField(
                        choices=[("keyframe", "关键帧"), ("interframe", "中间帧")],
                        default="keyframe",
                        max_length=20,
                        verbose_name="帧类型",
                    ),
                ),
                (
                    "video_stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="webrtc.videostream",
                    ),
                ),
            ],
            options={
                "verbose_name": "视频帧",
                "verbose_name_plural": "视频帧",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WebRTCConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="会话ID"
                    ),
                ),
                ("peer_id", models.CharField(max_length=100, verbose_name="对等端ID")),
                (
                    "connection_state",
                    models.CharField(
                        choices=[
                            ("new", "新建"),
                            ("connecting", "连接中"),
                            ("connected", "已连接"),
                            ("disconnected", "已断开"),
                            ("failed", "连接失败"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="连接状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "video_stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="webrtc.videostream",
                    ),
                ),
            ],
            options={
                "verbose_name": "WebRTC连接",
                "verbose_name_plural": "WebRTC连接",
                "ordering": ["-created_at"],
            },
        ),
    ]
