# Generated by Django 5.2.4 on 2025-08-15 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProblemBank",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="题库ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="题库标题")),
                ("description", models.TextField(verbose_name="题库描述")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("前端开发", "前端开发"),
                            ("后端开发", "后端开发"),
                            ("算法设计", "算法设计"),
                            ("测试开发", "测试开发"),
                            ("产品经理", "产品经理"),
                            ("数据分析", "数据分析"),
                        ],
                        max_length=50,
                        verbose_name="分类",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "简单"),
                            ("Medium", "中等"),
                            ("Hard", "困难"),
                        ],
                        max_length=20,
                        verbose_name="难度",
                    ),
                ),
                (
                    "problem_count",
                    models.IntegerField(default=0, verbose_name="题目总数"),
                ),
                (
                    "completed_count",
                    models.IntegerField(default=0, verbose_name="已完成数量"),
                ),
                ("tags", models.JSONField(default=list, verbose_name="标签")),
                (
                    "color",
                    models.CharField(
                        default="bg-purple-300", max_length=50, verbose_name="颜色主题"
                    ),
                ),
                (
                    "is_algorithm",
                    models.BooleanField(default=False, verbose_name="是否为算法题"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "题库",
                "verbose_name_plural": "题库",
                "ordering": ["category", "difficulty", "title"],
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="题目ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("前端开发", "前端开发"),
                            ("后端开发", "后端开发"),
                            ("算法设计", "算法设计"),
                            ("测试开发", "测试开发"),
                            ("产品经理", "产品经理"),
                            ("数据分析", "数据分析"),
                        ],
                        max_length=50,
                        verbose_name="分类",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="题目标题")),
                ("description", models.TextField(verbose_name="题目描述")),
                ("scenario", models.TextField(verbose_name="场景描述")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "简单"),
                            ("Medium", "中等"),
                            ("Hard", "困难"),
                        ],
                        max_length=20,
                        verbose_name="难度",
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="标签")),
                ("question", models.TextField(verbose_name="问题内容")),
                ("reference_answer", models.TextField(verbose_name="参考答案")),
                ("analysis", models.TextField(verbose_name="题目分析")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="code_execution.problembank",
                        verbose_name="所属题库",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目",
                "verbose_name_plural": "题目",
                "ordering": ["problem_set", "difficulty", "title"],
            },
        ),
    ]
