# Generated by Django 5.2.4 on 2025-08-15 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_execution", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemSubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="提交ID"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                ("total_score", models.FloatField(default=0, verbose_name="总分")),
                (
                    "total_problems",
                    models.IntegerField(default=0, verbose_name="总题数"),
                ),
                (
                    "correct_count",
                    models.IntegerField(default=0, verbose_name="正确题数"),
                ),
                (
                    "overall_analysis",
                    models.TextField(blank=True, verbose_name="整体评析"),
                ),
                (
                    "improvement_suggestions",
                    models.TextField(blank=True, verbose_name="改进建议"),
                ),
                (
                    "problem_bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="code_execution.problembank",
                        verbose_name="题库",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "答题提交记录",
                "verbose_name_plural": "答题提交记录",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ProblemAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.TextField(verbose_name="用户答案")),
                ("score", models.FloatField(default=0, verbose_name="得分")),
                ("max_score", models.FloatField(default=10, verbose_name="满分")),
                ("analysis", models.TextField(blank=True, verbose_name="评析")),
                ("strengths", models.TextField(blank=True, verbose_name="优点")),
                ("weaknesses", models.TextField(blank=True, verbose_name="不足")),
                ("suggestions", models.TextField(blank=True, verbose_name="建议")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="code_execution.problem",
                        verbose_name="题目",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="code_execution.problemsubmission",
                        verbose_name="提交记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "单题答题记录",
                "verbose_name_plural": "单题答题记录",
                "ordering": ["submission", "problem"],
            },
        ),
    ]
