# Generated by Django 5.2.4 on 2025-08-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_execution", "0002_problemsubmission_problemanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="algorithm_code_template",
            field=models.TextField(
                blank=True, null=True, verbose_name="算法题代码模板"
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="algorithm_constraints",
            field=models.JSONField(
                blank=True, null=True, verbose_name="算法题约束条件"
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="algorithm_solution",
            field=models.TextField(blank=True, null=True, verbose_name="算法题解答"),
        ),
        migrations.AddField(
            model_name="problem",
            name="algorithm_test_cases",
            field=models.JSONField(
                blank=True, null=True, verbose_name="算法题测试用例"
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="is_algorithm",
            field=models.BooleanField(default=False, verbose_name="是否为算法题"),
        ),
        migrations.AddField(
            model_name="problem",
            name="non_algorithm_knowledge_points",
            field=models.JSONField(
                blank=True, null=True, verbose_name="非算法题知识点"
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="non_algorithm_scoring_criteria",
            field=models.JSONField(
                blank=True, null=True, verbose_name="非算法题评分标准"
            ),
        ),
    ]
