# Generated by Django 5.2.4 on 2025-07-20 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("knowledge_base", "0002_jobposition_position_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interview_time", models.DateTimeField(verbose_name="面试时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "position_name",
                    models.CharField(max_length=100, verbose_name="岗位名称"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="公司名称"
                    ),
                ),
                ("position_description", models.TextField(verbose_name="岗位详细信息")),
                (
                    "position_requirements",
                    models.TextField(blank=True, null=True, verbose_name="岗位要求"),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("backend", "后端开发"),
                            ("frontend", "前端开发"),
                            ("pm", "产品经理"),
                            ("qa", "测试"),
                            ("algo", "算法"),
                        ],
                        default="backend",
                        max_length=20,
                        verbose_name="岗位类型",
                    ),
                ),
                (
                    "job_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="knowledge_base.jobposition",
                        verbose_name="关联岗位",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "面试",
                "verbose_name_plural": "面试",
                "ordering": ["-interview_time"],
            },
        ),
    ]
