# Generated by Django 5.2.4 on 2025-08-12 05:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "radar_dimensions",
                    models.JSONField(default=list, verbose_name="雷达图维度"),
                ),
                (
                    "radar_scores",
                    models.JSONField(default=list, verbose_name="雷达图分数"),
                ),
                (
                    "radar_comment",
                    models.TextField(blank=True, verbose_name="雷达图评论"),
                ),
                (
                    "pie_points",
                    models.JSONField(default=list, verbose_name="知识点分布数据"),
                ),
                (
                    "pie_comment",
                    models.TextField(blank=True, verbose_name="知识点分布评论"),
                ),
                (
                    "bar_labels",
                    models.JSONField(default=list, verbose_name="知识点标签"),
                ),
                (
                    "bar_accuracy",
                    models.JSONField(default=list, verbose_name="知识点掌握度"),
                ),
                (
                    "bar_comment",
                    models.TextField(blank=True, verbose_name="知识点掌握度评论"),
                ),
                ("total_score", models.FloatField(default=0, verbose_name="总分")),
                (
                    "last_compare",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="与上次面试对比"
                    ),
                ),
                ("star_summary", models.TextField(blank=True, verbose_name="STAR总结")),
                (
                    "technical_summary",
                    models.TextField(blank=True, verbose_name="技术总结"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_results",
                        to="interviews.interview",
                        verbose_name="面试",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "面试评估结果",
                "verbose_name_plural": "面试评估结果",
                "ordering": ["-created_at"],
                "unique_together": {("interview", "user")},
            },
        ),
    ]
