# Generated by Django 5.2.4 on 2025-08-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_interviewresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="知识点名称"
                    ),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("backend", "后端开发"),
                            ("frontend", "前端开发"),
                            ("pm", "产品经理"),
                            ("qa", "测试"),
                            ("algo", "算法"),
                            ("data", "数据"),
                        ],
                        max_length=20,
                        verbose_name="适用岗位类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="知识点描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "知识点标签",
                "verbose_name_plural": "知识点标签",
                "ordering": ["position_type", "name"],
            },
        ),
    ]
