# Generated by Django 5.2.4 on 2025-07-20 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_interviewanswer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodingProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="题目序号"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="题目标题")),
                ("description", models.TextField(verbose_name="题目描述")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "简单"),
                            ("medium", "中等"),
                            ("hard", "困难"),
                        ],
                        max_length=10,
                        verbose_name="难度等级",
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="题目标签")),
                ("companies", models.JSONField(default=list, verbose_name="出题公司")),
                (
                    "position_types",
                    models.JSONField(default=list, verbose_name="适用岗位类型"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "代码题",
                "verbose_name_plural": "代码题",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="CodingExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField(verbose_name="样例输入")),
                ("output_data", models.TextField(verbose_name="样例输出")),
                ("explanation", models.TextField(blank=True, verbose_name="解释说明")),
                ("order", models.IntegerField(default=1, verbose_name="顺序")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examples",
                        to="interviews.codingproblem",
                        verbose_name="代码题",
                    ),
                ),
            ],
            options={
                "verbose_name": "代码题样例",
                "verbose_name_plural": "代码题样例",
                "ordering": ["problem", "order"],
            },
        ),
        migrations.CreateModel(
            name="InterviewCodingAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_answer", models.TextField(verbose_name="代码答案")),
                (
                    "language",
                    models.CharField(
                        default="python", max_length=50, verbose_name="编程语言"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="答题时间"),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_answers",
                        to="interviews.interview",
                        verbose_name="面试",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interviews.codingproblem",
                        verbose_name="代码题",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "面试代码题答题记录",
                "verbose_name_plural": "面试代码题答题记录",
                "ordering": ["created_at"],
            },
        ),
    ]
