# Generated by Django 5.2.4 on 2025-07-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0003_codingproblem_codingexample_interviewcodinganswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewanswer",
            name="ai_analysis",
            field=models.TextField(blank=True, null=True, verbose_name="AI分析结果"),
        ),
        migrations.AddField(
            model_name="interviewanswer",
            name="confidence_score",
            field=models.FloatField(default=0, verbose_name="信心得分"),
        ),
        migrations.AddField(
            model_name="interviewanswer",
            name="fluency_score",
            field=models.FloatField(default=0, verbose_name="流畅度得分"),
        ),
    ]
