# Generated by Django 5.2.4 on 2025-07-21 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0004_interviewanswer_ai_analysis_and_more"),
        ("users", "0003_alter_resume_options_resume_completed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="resume",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interviews",
                to="users.resume",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
