# Generated by Django 5.2.4 on 2025-07-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0006_alter_interview_resume_alter_interview_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="question_queue",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="存储个性化推荐的面试问题列表",
                verbose_name="面试问题队列",
            ),
        ),
    ]
