# Generated by Django 5.2.4 on 2025-07-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0008_update_interview_position_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewanswer",
            name="confidence_score",
        ),
        migrations.RemoveField(
            model_name="interviewanswer",
            name="fluency_score",
        ),
        migrations.AddField(
            model_name="interviewanswer",
            name="communication_skills",
            field=models.FloatField(default=0, verbose_name="语言表达能力"),
        ),
        migrations.AddField(
            model_name="interviewanswer",
            name="innovation_ability",
            field=models.FloatField(default=0, verbose_name="创新能力"),
        ),
        migrations.AddField(
            model_name="interviewanswer",
            name="logical_thinking",
            field=models.FloatField(default=0, verbose_name="逻辑思维能力"),
        ),
        migrations.AddField(
            model_name="interviewanswer",
            name="professional_knowledge",
            field=models.FloatField(default=0, verbose_name="专业知识水平"),
        ),
        migrations.AddField(
            model_name="interviewanswer",
            name="skill_matching",
            field=models.FloatField(default=0, verbose_name="技能匹配度"),
        ),
        migrations.AddField(
            model_name="interviewanswer",
            name="stress_handling",
            field=models.FloatField(default=0, verbose_name="应变抗压能力"),
        ),
    ]
