# Generated by Django 5.2.4 on 2025-07-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0009_remove_interview_job_position_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="job_position",
        ),
        migrations.AddField(
            model_name="interviewanswer",
            name="correctness_score",
            field=models.FloatField(default=0, verbose_name="回答正确性得分"),
        ),
        migrations.AddField(
            model_name="interviewanswer",
            name="knowledge_points",
            field=models.JSONField(default=list, verbose_name="知识点列表"),
        ),
    ]
