# Generated by Django 5.2.4 on 2025-07-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0010_remove_interview_job_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewanswer",
            name="knowledge_points",
            field=models.JSONField(default=list, verbose_name="问题知识点"),
        ),
    ]
