# Generated by Django 5.2.4 on 2025-07-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0011_alter_interviewanswer_knowledge_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewanswer",
            name="correctness_score",
            field=models.FloatField(
                default=0,
                help_text="回答正确性评分(1-5分)",
                verbose_name="答案正确性分数",
            ),
        ),
        migrations.AlterField(
            model_name="interviewanswer",
            name="knowledge_points",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="该问题涉及的具体知识点列表",
                verbose_name="问题知识点",
            ),
        ),
    ]
